/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.spotify.ui.LoginRegister;

import com.spotify.app.Account;
import com.spotify.app.Admin;
import com.spotify.app.User;
import com.spotify.ui.Window;
import com.spotify.ui.admin.WindowAdmin;

import javax.swing.*;
import java.awt.*;
import java.awt.event.*;
import java.util.ArrayList;
import java.util.Arrays;

/**
 *
 * @author KEVIN
 */
public class Flogin extends javax.swing.JFrame {

    public Flogin(ArrayList<Account> accounts) {
        System.out.println(accounts.size());
        initComponents(accounts);
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">
    private void initComponents(ArrayList<Account> accounts) {
        Login = new javax.swing.JPanel();
        lbtitlelogin = new javax.swing.JLabel();
        lbemail = new javax.swing.JLabel();
        lblogo = new javax.swing.JLabel();
        lbpassword_no = new javax.swing.JLabel();
        lbpassword_see = new javax.swing.JLabel();
        pflogin = new javax.swing.JPasswordField();
        lbResetPassword = new javax.swing.JLabel();
        lblogin = new javax.swing.JLabel();
        lbSignUp = new javax.swing.JLabel();
        lbMsg1 = new javax.swing.JLabel();
        tfemailusername = new javax.swing.JTextField();
        lbexit = new javax.swing.JLabel();
        this.setAutoRequestFocus(false);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setName("frameLogin");
        setUndecorated(true);

        Login.setBackground(new java.awt.Color(18, 18, 18));
        Login.setForeground(new java.awt.Color(255, 255, 255));
        Login.setPreferredSize(new java.awt.Dimension(500, 600));
        Login.setLayout(null);

        lbtitlelogin.setFont(new java.awt.Font("Gotham", 1, 30));
        lbtitlelogin.setForeground(new java.awt.Color(255, 255, 255));
        lbtitlelogin.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbtitlelogin.setText("Log in to continue.");
        Login.add(lbtitlelogin);
        lbtitlelogin.setBounds(100, 120, 290, 53);

        lbemail.setBackground(new java.awt.Color(0, 0, 0));
        lbemail.setForeground(new java.awt.Color(255, 255, 255));
        lbemail.setIcon(new javax.swing.ImageIcon(
            getClass().getResource("/com/spotify/assets/loginRegister/email_icon.png")
        ));
        Login.add(lbemail);
        lbemail.setBounds(365, 190, 50, 40);

        lblogo.setBackground(new java.awt.Color(51, 51, 51));
        lblogo.setForeground(new java.awt.Color(255, 255, 255));
        lblogo.setIcon(new javax.swing.ImageIcon(
            getClass().getResource("/com/spotify/assets/loginRegister/logo_Login_Spotify.png")
        ));
        lblogo.setText("logo");
        Login.add(lblogo);
        lblogo.setBounds(170, 40, 160, 50);

        lbpassword_no.setForeground(new java.awt.Color(255, 255, 255));
        lbpassword_no.setIcon(new javax.swing.ImageIcon(
            getClass().getResource("/com/spotify/assets/loginRegister/pass_no_icon.png")
        ));
        lbpassword_no.setText("pass");
        lbpassword_no.addMouseListener(new java.awt.event.MouseAdapter() {
            @Override
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbpassword_noMouseClicked(evt);
            }
        });
        Login.add(lbpassword_no);
        lbpassword_no.setBounds(363, 250, 50, 40);

        lbpassword_see.setBackground(new java.awt.Color(0, 0, 0));
        lbpassword_see.setForeground(new java.awt.Color(255, 255, 255));
        lbpassword_see.setIcon(new javax.swing.ImageIcon(
            getClass().getResource("/com/spotify/assets/loginRegister/pass_see_icon.png")
        ));
        lbpassword_see.addMouseListener(new java.awt.event.MouseAdapter() {
            @Override
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbpassword_seeMouseClicked(evt);
            }
        });
        Login.add(lbpassword_see);
        lbpassword_see.setBounds(360, 250, 50, 40);

        pflogin.setEchoChar('*');
        pflogin.setBackground(new java.awt.Color(51, 51, 51));
        pflogin.setFont(new java.awt.Font("Gotham", 0, 14));
        pflogin.setForeground(new java.awt.Color(179, 179, 179));
        pflogin.setText("Password");
        pflogin.setCaretColor(Color.WHITE);
        pflogin.setBorder(javax.swing.BorderFactory.createEmptyBorder(5, 10, 10, 5));
        pflogin.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        pflogin.addFocusListener(new FocusAdapter() {
            @Override
            public void focusGained(FocusEvent e) {
                super.focusGained(e);
                char[] temp={'P','a','s','s','w','o','r','d'};
                if(Arrays.equals(pflogin.getPassword(),temp)){
                    pflogin.setText("");
                }
            }

            @Override
            public void focusLost(FocusEvent e) {
                super.focusLost(e);
                char[] temp={};
                if(Arrays.equals(pflogin.getPassword(),temp)){
                    pflogin.setText("Password");
                }
            }
        });
        Login.add(pflogin);
        pflogin.setBounds(70, 250, 300, 40);

        lbResetPassword.setFont(new java.awt.Font("Gotham", 0, 14));
        lbResetPassword.setForeground(new java.awt.Color(179, 179, 179));
        lbResetPassword.setText("Reset Password");
        lbResetPassword.addMouseListener(new java.awt.event.MouseAdapter() {
            @Override
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbResetPasswordMouseClicked(evt, accounts);
            }
        });
        Login.add(lbResetPassword);
        lbResetPassword.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lbResetPassword.setBounds(70, 300, 130, 20);

        lblogin.setForeground(new java.awt.Color(255, 255, 255));
        lblogin.setIcon(new javax.swing.ImageIcon(
            getClass().getResource("/com/spotify/assets/loginRegister/log_in_btn.png")
        ));
        lblogin.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Login.add(lblogin);
        lblogin.addMouseListener(new MouseAdapter() {
            @Override
            public void mouseClicked(MouseEvent e) {
                super.mouseClicked(e);
                lbloginMouseClicked(e, accounts);
            }
        });
        lblogin.setBounds(60, 330, 350, 50);

        lbSignUp.setFont(new java.awt.Font("Gotham", 1, 15));
        lbSignUp.setForeground(new java.awt.Color(179, 179, 179));
        lbSignUp.setText("SIGNUP");
        lbSignUp.setToolTipText("");
        lbSignUp.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lbSignUp.addMouseListener(new java.awt.event.MouseAdapter() {
            @Override
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbSignUpMouseClicked(evt, accounts);
            }
        });
        Login.add(lbSignUp);
        lbSignUp.setBounds(290, 400, 60, 20);

        lbMsg1.setFont(new java.awt.Font("Gotham", 1, 15));
        lbMsg1.setForeground(new java.awt.Color(179, 179, 179));
        lbMsg1.setText("Don't have an account?");
        Login.add(lbMsg1);
        lbMsg1.setBounds(120, 400, 200, 20);

        tfemailusername.setBackground(new java.awt.Color(51, 51, 51));
        tfemailusername.setFont(new java.awt.Font("Gotham", 0, 14));
        tfemailusername.setForeground(new java.awt.Color(179, 179, 179));
        tfemailusername.setText("Email or Username");
        tfemailusername.setCaretColor(Color.WHITE);
        tfemailusername.setBorder(javax.swing.BorderFactory.createEmptyBorder(5, 5, 5, 5));
        tfemailusername.addFocusListener(new java.awt.event.FocusAdapter() {
            @Override
            public void focusGained(java.awt.event.FocusEvent evt) {
                tfemailusernameFocusGained(evt);
            }

            @Override
            public void focusLost(java.awt.event.FocusEvent evt) {
                tfemailusernameFocusLost(evt);
            }
        });

        Login.add(tfemailusername);
        tfemailusername.setBounds(70, 190, 300, 40);

        lbexit.setFont(new java.awt.Font("Gotham", 1, 20));
        lbexit.setForeground(new java.awt.Color(255, 255, 255));
        lbexit.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lbexit.setText("X");
        lbexit.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lbexit.addMouseListener(new java.awt.event.MouseAdapter() {
            @Override
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbexitMouseClicked(evt);
            }
        });
        Login.add(lbexit);
        lbexit.setBounds(420, 10, 40, 50);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Login, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Login, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        setBounds(650, 250, 484, 561);
        setLocationRelativeTo(null);
    }// </editor-fold>

    private void lbloginMouseClicked(java.awt.event.MouseEvent evt, ArrayList<Account> accounts) {
        String username = tfemailusername.getText();
        String password = String.valueOf(pflogin.getPassword());

        if(username.equals("admin") && password.equals("admin")) {
            Admin admin = (Admin)accounts.get(0);
            this.setVisible(false);
            WindowAdmin windowAdmin = new WindowAdmin(admin, accounts);
        } else {
            boolean usernameIsCorrect = false;
            boolean passwordIsCorrect = false;
            User userLogin = null;
            for(Account account : accounts) {
                if(account instanceof User) {
                    User user = (User) account;
                    if(user.getUsername().equals(username) || user.getEmail().equals(username)) {
                        usernameIsCorrect = true;
                        if(user.getPassword().equals(password)) {
                            passwordIsCorrect = true;
                            userLogin = (User)account;
                        }
                    }
                }
            }

            if(!usernameIsCorrect) {
                System.out.println("Invalid Username!");
                JOptionPane.showMessageDialog(null, "Wrong username!");
            }
            else if(!passwordIsCorrect) {
                System.out.println("Valid Username but wrong password!");
                JOptionPane.showMessageDialog(null, "Wrong password!");
            }
            else if(usernameIsCorrect && passwordIsCorrect) {
                System.out.println("Valid username and password is correct");
                this.setVisible(false);
                Window window = new Window(userLogin, accounts);
            }
        }
    }

    private void lbpassword_noMouseClicked(java.awt.event.MouseEvent evt) {
        pflogin.setEchoChar((char)0);
        lbpassword_no.setVisible(false);
        lbpassword_see.setVisible(true);
    }

    private void lbpassword_seeMouseClicked(java.awt.event.MouseEvent evt) {
        pflogin.setEchoChar('*');
        lbpassword_see.setVisible(false);
        lbpassword_no.setVisible(true);
    }

    private void lbSignUpMouseClicked(java.awt.event.MouseEvent evt, ArrayList<Account> accounts) {
        this.setVisible(false);
        Fregister r = new Fregister(accounts);
        r.setVisible(true);
    }

    private void tfemailusernameFocusGained(java.awt.event.FocusEvent evt) {
        if(tfemailusername.getText().trim().equals("Email or Username")) {
            tfemailusername.setText("");
        }
    }

    private void tfemailusernameFocusLost(java.awt.event.FocusEvent evt) {
        if(tfemailusername.getText().trim().equals("") || tfemailusername.getText().trim().equals("Email or Username")) {
            tfemailusername.setText("Email or Username");
        }
    }

    private void lbexitMouseClicked(java.awt.event.MouseEvent evt) {
        System.exit(0);
    }

    private void lbResetPasswordMouseClicked(java.awt.event.MouseEvent evt, ArrayList<Account> accounts) {
        this.setVisible(false);
        FQuestionVerify q = new FQuestionVerify(accounts);
        q.setVisible(true);
    }

//    /**
//     * @param args the command line arguments
//     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(Flogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(Flogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(Flogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(Flogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new Flogin().setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Login;
    private javax.swing.JLabel lbMsg1;
    private javax.swing.JLabel lbResetPassword;
    private javax.swing.JLabel lbSignUp;
    private javax.swing.JLabel lbemail;
    private javax.swing.JLabel lbexit;
    private javax.swing.JLabel lblogin;
    private javax.swing.JLabel lblogo;
    private javax.swing.JLabel lbpassword_no;
    private javax.swing.JLabel lbpassword_see;
    private javax.swing.JLabel lbtitlelogin;
    private javax.swing.JPasswordField pflogin;
    private javax.swing.JTextField tfemailusername;
    // End of variables declaration//GEN-END:variables
}
